#!/usr/bin/python
# -*- coding:utf8 -*-

import os
import sys

# Output: lib/generated/assets.dart (Assets class)
EXT_PATH = 'lib/generated/assets.dart'
path_image_list = []
path_image_file = []


def foreach_file(path):
    pathlist = os.listdir(path)
    for file in pathlist:
        pathfil = path + '/' + file
        if os.path.isdir(pathfil):
            path_image_file.append(pathfil)
            foreach_file(pathfil)
        else:
            base = os.path.basename(pathfil)
            if base.startswith('.') or base == 'resource_gen_script.py':
                continue
            ext = os.path.splitext(base)[1].lower()
            if ext not in ('.png', '.jpg', '.jpeg', '.webp', '.svg', '.gif', '.ttf', '.otf'):
                continue
            path_image_list.append(pathfil)


def _segment_to_camel(seg):
    """Convert a segment (e.g. 'ic_back', 'gb-eng') to PascalCase."""
    words = seg.replace('-', '_').split('_')
    return ''.join(w.capitalize() for w in words) if words else seg


def _parts_to_camel(parts):
    """Convert path parts to camelCase (first letter lower)."""
    s = ''.join(_segment_to_camel(p) for p in parts)
    return s[0].lower() + s[1:] if len(s) > 1 else s.lower()


def path_to_constant_name(relative_path):
    """
    Convert relative asset path to Assets constant name.
    e.g. 'images/common/ic_back.svg' -> 'commonIcBack'
         'resource_gen_script.py' -> 'assetsResourceGenScript'
    """
    parts = relative_path.replace('\\', '/').split('/')
    if not parts:
        return None
    # Remove extension from last part
    last = parts[-1]
    if '.' in last:
        parts[-1] = last.rsplit('.', 1)[0]
    if not parts:
        return None
    # Drop leading 'images' segment to match assets.dart style
    if parts[0] == 'images':
        parts = parts[1:]
    if not parts:
        return None
    if len(parts) == 1:
        return 'assets' + _segment_to_camel(parts[0])
    return _parts_to_camel(parts)


def build_assets_dart_content(assets_root_path):
    """Build the full Dart source for Assets class."""
    lines = [
        '///This file is automatically generated. DO NOT EDIT, all your changes would be lost.',
        'class Assets {',
        '  Assets._();',
        '',
    ]
    prefix = assets_root_path.rstrip('/') + '/'
    for file_path in sorted(path_image_list):
        rel = file_path.replace(prefix, '').replace('\\', '/')
        const_name = path_to_constant_name(rel)
        if not const_name:
            continue
        asset_path = 'assets/' + rel
        lines.append("  static const String %s = '%s';" % (const_name, asset_path))
    lines.append('')
    lines.append('}')
    return '\n'.join(lines)


def write_dart(dart_path, assets_root_path):
    content = build_assets_dart_content(assets_root_path)
    os.makedirs(os.path.dirname(dart_path), exist_ok=True)
    with open(dart_path, 'w', encoding='utf-8') as f:
        f.write(content)


def write_yaml(assets_root_path):
    """Update pubspec.yaml with asset directories (between # assets-generator markers)."""
    app_root = assets_root_path.replace(r'assets', '').rstrip('/')
    yaml_path = os.path.join(app_root, 'pubspec.yaml')
    if not os.path.isfile(yaml_path):
        return
    with open(yaml_path, 'r', encoding='utf-8') as f:
        line = f.readlines()
    # Keep logic: find # assets-generator-begin / end and inject dirs
    path_image_file_sorted = sorted(path_image_file)
    image_filegrop = assets_root_path.split('/')
    index = 0
    begin = 0
    writebool = True
    msg = []
    for yamlMsg in line:
        index += 1
        if '# assets-generator-begin' in yamlMsg:
            begin = index
            msg.append(yamlMsg)
            writebool = False
        if '# assets-generator-end' in yamlMsg:
            writebool = True
        if writebool:
            msg.append(yamlMsg)
    for path_file in path_image_file_sorted:
        dart_path = path_file.replace((assets_root_path + '/'), '')
        pathgroup = dart_path.split('/')
        s = '    - assets'
        for p in pathgroup:
            s += '/' + p
        s += '/\n'
        msg.insert(begin, s)
        begin += 1
    with open(yaml_path, 'w', encoding='utf-8') as yamlfile:
        yamlfile.writelines(msg)


if __name__ == '__main__':
    path = sys.path[0]
    foreach_file(path)
    # Resolve app root: script lives in app/assets, so path = .../app/assets
    app_root = path.replace(os.path.sep + 'assets', '').replace('/assets', '')
    dart_path = os.path.join(app_root, EXT_PATH)
    write_dart(dart_path, path)
    write_yaml(path)
