/// Map of API error `message_id` to English user-facing text.
const Map<String, String> kErrorMessageMap = {
  'common_error_01': 'System error, try again later.',
  'undefined': 'Your account has been disabled. Please contact support.',
  'common_error_02': 'Too many attempts. Please try again later.',
  'common_error_03': 'System error, try again later.',
  'common_error_04': 'System error, try again later.',
  'common_error_05': 'System error, try again later.',
  'common_error_06': 'System error, try again later.',
  'common_error_07': 'System error, try again later.',
  'common_error_08': 'System error, try again later.',
  'error_01': 'System error, try again later.',
  'error_02': 'System error, try again later.',
  'error_03': 'System error, try again later.',
  'error_04': 'System error, try again later.',
  'error_05': 'System error, try again later.',
  'error_06': 'System error, try again later.',
  'error_07': 'System error, try again later.',
  'error_08': 'System error, try again later.',
  'login_error_01': 'Incorrect email or password.',
  'login_error_02': 'Invalid email format.',
  'login_error_03': 'Email is required.',
  'login_error_04': 'Invalid user role. Use "patient" or "user"',
  'login_error_05': 'Incorrect email or password.',
  'login_error_06': 'Login for non-patient roles is not yet implemented',
  'login_error_07':
      'Your account is scheduled for deletion. Access is restricted during the 30-day cooling-off period. If you wish to cancel this request and restore your account, please contact the clinic administration.',
  'request_otp_error_01': 'Email is required.',
  'request_otp_error_02': 'Invalid email format.',
  'request_otp_error_03': 'This email is already registered. Please Log In or Reset Password.',
  'verify_otp_error_01': 'Email is required.',
  'verify_otp_error_02': 'Invalid email format.',
  'verify_otp_error_03': 'OTP is required.',
  'verify_otp_error_04': 'Invalid or expired code. Please try again.',
  'resend_otp_error_01': 'Email is required.',
  'request_otp_error_04': 'This email address is currently linked to an account scheduled for deletion. You cannot create a new account with this email until the 30-day cooling-off period has expired.',
  'resend_otp_error_02': 'Invalid email format.',
  'resend_otp_error_03': 'This email is already registered. Please Log In or Reset Password.',
  'resend_otp_error_04': 'Too many attempts. Please try again later.',
  'resend_otp_error_05': 'Failed to generate new OTP. Please try again.',
  'resend_otp_error_06': 'Failed to send OTP to your email. Please try again.',
  'resend_otp_error_07': 'System error, try again later.',
  'resend_otp_error_08': 'No account found with this email address.',
  'password_error_01': 'Password is required.',
  'password_error_02': 'Confirm Password is required.',
  'password_error_03': 'Password is invalid.',
  'password_error_04': 'Passwords do not match.',
  'profile_error_01': 'First name is required.',
  'profile_error_02': 'Name must be at least 2 characters long.',
  'profile_error_03': 'Name can only contain letters.',
  'profile_error_04': 'Last name is required.',
  'profile_error_05': 'Name must be at least 2 characters long.',
  'profile_error_06': 'Name can only contain letters.',
  'profile_error_07': 'Title is required.',
  'profile_error_08': 'Date of Birth is required.',
  'profile_error_09': 'Invalid date of birth.',
  'profile_error_10': 'Date of Birth must be in the past.',
  'profile_error_11': 'Phone Number is required.',
  'profile_error_12': 'Invalid phone number format.',
  'profile_error_13': 'Sex at Birth is required.',
  'profile_error_14': 'Country of Origin is required.',
  'appointment_error_01': 'Appointment not found.',
  'appointment_error_02': 'This slot is no longer available.',
  'appointment_error_03': 'Required field is missing.',
  'appointment_error_04': 'Invalid selection. Please try again.',
  'appointment_error_05': 'Invalid selection. Please try again.',
  'appointment_error_06': 'Invalid selection. Please try again.',
  'appointment_error_07': 'Invalid selection. Please try again.',
  'appointment_error_08': 'Invalid selection. Please try again.',
  'appointment_error_09': 'Invalid selection. Please try again.',
  'appointment_error_10': 'Invalid selection. Please try again.',
  'appointment_error_11': 'Invalid selection. Please try again.',
  'appointment_error_12': 'Cannot book an appointment in the past.',
  'appointment_error_13': 'Too long search keywords.',
  'appointment_error_14': 'Date and time are required.',
  'appointment_error_15': 'Required parameter is missing.',
  'appointment_error_16': 'Guest information is incomplete.',
  'appointment_error_17': 'System error, try again later.',
  'appointment_error_18': 'Reschedule is missing required field.',
  'appointment_error_19': 'System error, try again later.',
  'patient_error_1': 'System error, try again later.',
  'patient_error_2': 'System error, try again later.',
  'patient_error_3': 'System error, try again later.',
  'patient_error_4': 'System error, try again later.',
  'medical_error_1': 'Your Medical Profile has been archived in our system. Please contact our medical staff for support.',
  'medical_error_2':
      'We could not automatically link your account due to a system conflict. For your safety, please contact our support hotline so our staff can assist you.',
  'medical_error_3':
      'We found a matching medical profile, but it is already connected with a different mobile account. Please verify your login details or contact our medical staff for support.',
  'medical_error_4': 'Sharing consent is required.',
  'medical_error_5': 'You haven\'t linked your medical profile yet.',
  'refresh_token_error_01': 'System error, try again later.',
  'refresh_token_error_02': 'System error, try again later.',
  'logout_error_01': 'System error, try again later.',
  'change_password_error_01': 'Current password is required.',
  'change_password_error_02': 'Current password is incorrect.',
  'change_password_error_03': 'New password is required.',
  'change_password_error_04': 'New password format is invalid.',
  'change_password_error_05': 'For security, you cannot reuse any of your last 5 passwords.',
  'change_password_error_06': 'Confirm password is required.',
  'change_password_error_07': 'Passwords do not match.',
  'forgot_password_request_otp_error_01': 'Email is required.',
  'forgot_password_request_otp_error_02': 'Invalid email format.',
  'forgot_password_request_otp_error_03': 'Email does not exist in the system.',
  'forgot_password_request_otp_error_04':
      'Your account is scheduled for deletion. Access is restricted during the 30-day cooling-off period. If you wish to cancel this request and restore your account, please contact the clinic administration.',
  'forgot_password_verify_otp_error_01': 'Email is required.',
  'forgot_password_verify_otp_error_02': 'Invalid email format.',
  'forgot_password_verify_otp_error_03': 'OTP is required.',
  'forgot_password_verify_otp_error_04': 'Invalid or expired code. Please try again.',
  'forgot_password_verify_otp_error_05': 'Email does not exist in the system.',
  'forgot_password_resend_otp_error_01': 'Email is required.',
  'forgot_password_resend_otp_error_02': 'Invalid email format.',
  'forgot_password_resend_otp_error_03': 'Email does not exist in the system.',
  'forgot_password_resend_otp_error_04': 'Too many attempts. Please try again later.',
  'forgot_password_resend_otp_error_05':
      'Your account is scheduled for deletion. Access is restricted during the 30-day cooling-off period. If you wish to cancel this request and restore your account, please contact the clinic administration.',
  'forgot_password_reset_password_error_01': 'Password is required.',
  'forgot_password_reset_password_error_02': 'Confirm password is required.',
  'forgot_password_reset_password_error_03': 'Password is invalid.',
  'forgot_password_reset_password_error_04': 'Passwords do not match.',
  'forgot_password_reset_password_error_05': 'For security, you cannot reuse any of your last 5 passwords.',
  'medical_file_error_01': 'Document not found. Please contact the clinic or wait for the document updates.',
  'visit_error_01': 'There are no visits or medical documents available for the selected date range.',
  'consent_error_01': 'Document not found. Please contact the clinic or wait for the document updates.',
  'consent_error_02': 'Unsupported document type. Only images (JPEG, PNG, JPG, JPEG) and PDF files are supported.',
  'data_sharing_consent_error_01': 'System error, try again later.',
  'data_sharing_consent_error_02': 'System error, try again later.',
  'data_sharing_consent_error_03': 'System error, try again later.',
  'data_sharing_consent_error_04': 'System error, try again later.',
  'data_sharing_consent_error_05': 'System error, try again later.',
  'data_sharing_consent_error_06': 'System error, try again later.',
  'medical_success_2': 'Contact the clinic to receive Medical Document for this visit.',
  'medical_success_3': 'Contact the clinic to receive Medical Document for this visit.',
  'app_error_999': 'System error, try again later.',
  'app_error_01': 'System error, try again later.',
  'refresh_token_error_03': 'Account is no longer active.',
  'refresh_token_error_04': 'Account access is restricted due to pending deletion request.',
  'login_error_08': 'Your account has been disabled. Please contact support.',
};

/// English error message for [errorKey] (e.g. `message_id` from API).
String getErrorMessage(String errorKey) {
  final key = errorKey.trim();
  final msg = kErrorMessageMap[key];
  if (msg != null && msg.trim().isNotEmpty) {
    return msg;
  }
  return key;
}
